services:
  - type: web
    name: barberia-web
    runtime: python
    plan: free
    buildCommand: "poetry install --no-root && poetry run python manage.py collectstatic --noinput && poetry run python manage.py migrate"
    startCommand: "poetry run gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "barberia-web.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: barberia-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: barberia-redis
          property: connectionString

  - type: redis
    name: barberia-redis
    plan: free
    ipAllowList: []

databases:
  - name: barberia-db
    plan: free
