# Generated by Django 5.2.14 on 2026-07-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_celular', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('atendido', 'Atendido')], default='confirmado', max_length=20)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('acepta_promociones', models.BooleanField(default=False, verbose_name='Acepta recibir promociones y novedades')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.barbero')),
            ],
        ),
    ]
