# Generated by Django 5.2.14 on 2026-05-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='acepta_promociones',
            field=models.BooleanField(default=False, verbose_name='Acepta recibir promociones y novedades'),
        ),
    ]
